# Generated by Django 6.0 on 2026-01-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, help_text='Property walkthrough video', null=True, upload_to='properties/videos/'),
        ),
    ]
